# Generated by Django 5.1.7 on 2025-03-10 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('items_per_page', models.PositiveIntegerField(default=25, verbose_name='Записей на странице')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='Тема оформления')),
                ('can_import_data', models.BooleanField(default=False, verbose_name='Может импортировать данные')),
                ('can_export_data', models.BooleanField(default=False, verbose_name='Может экспортировать данные')),
                ('can_view_logs', models.BooleanField(default=False, verbose_name='Может просматривать логи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
