# Generated by Django 5.1.7 on 2025-03-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_user_groups'),
        ('accounts', '0002_userprofile_totp_enabled_userprofile_totp_secret'),
    ]

    operations = [
    ]
