# Generated by Django 5.1.7 on 2025-03-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250313_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('user1', 'Пользователь 1 уровня'), ('user2', 'Пользователь 2 уровня')], default='user1', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
