# Generated by Django 5.1.7 on 2025-03-13 08:40

from django.db import migrations, models

def convert_user_type(apps, schema_editor):
    UserProfile = apps.get_model('accounts', 'UserProfile')
    for profile in UserProfile.objects.all():
        if profile.user_type == 'user1':
            profile.user_type = 1
        elif profile.user_type == 'user2':
            profile.user_type = 2
        elif profile.user_type == 'admin':
            profile.user_type = 0
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_user_type'),
    ]

    operations = [
        migrations.RunPython(convert_user_type),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Пользователь 1 уровня'), (2, 'Пользователь 2 уровня')], default=1, verbose_name='Тип пользователя'),
        ),
    ]
