# Generated by Django 5.1.7 on 2025-05-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_user_type_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Пользователь 1 уровня'), (2, 'Пользователь 2 уровня')], default=1, verbose_name='Тип пользователя'),
        ),
    ]
