# Generated by Django 5.1.7 on 2025-03-10 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('CREATE', 'Создание объекта'), ('UPDATE', 'Изменение объекта'), ('DELETE', 'Удаление объекта'), ('IMPORT', 'Импорт данных'), ('SEARCH', 'Поиск'), ('EXPORT', 'Экспорт данных'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип действия')),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время действия')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действий пользователя',
                'verbose_name_plural': 'Логи действий пользователей',
                'ordering': ['-action_time'],
                'indexes': [models.Index(fields=['user'], name='logs_userac_user_id_86285b_idx'), models.Index(fields=['action_type'], name='logs_userac_action__7e4b0d_idx'), models.Index(fields=['action_time'], name='logs_userac_action__c0936e_idx'), models.Index(fields=['content_type', 'object_id'], name='logs_userac_content_bf7ae6_idx')],
            },
        ),
    ]
