# Generated by Django 5.1.7 on 2025-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='duration_ms',
            field=models.FloatField(blank=True, null=True, verbose_name='Время обработки (ms)'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='method',
            field=models.CharField(default='GET', max_length=10, verbose_name='HTTP метод'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='path',
            field=models.CharField(default='/', max_length=255, verbose_name='Путь запроса'),
        ),
        migrations.AddField(
            model_name='useractionlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP код ответа'),
        ),
    ]
