# Generated by Django 5.1.7 on 2025-07-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_add_path_and_method_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='logical_session_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Группировка действий по логическим сессиям (gap-based)', null=True, verbose_name='Логическая сессия'),
        ),
    ]
