# Generated by Django 5.1.7 on 2025-07-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_useractionlog_logical_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='related_log',
            field=models.ForeignKey(blank=True, help_text='Связанный лог (цепочка действий)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.useractionlog'),
        ),
    ]
