# Generated by Django 5.1.7 on 2025-03-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscriber',
            name='subscribers_phone_n_369620_idx',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='import_id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='importhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='records_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество созданных записей'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='records_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество неудачных записей'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='records_updated',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество обновленных записей'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='processing', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='import_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscribers.importhistory', verbose_name='История импорта'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='imsi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IMSI'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='memo1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Memo1'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='memo2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Memo2'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='number',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='original_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оригинальный ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['number'], name='subscribers_number_22e515_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['imsi'], name='subscribers_imsi_9b0f42_idx'),
        ),
    ]
