# Generated by Django 5.1.7 on 2025-03-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_remove_subscriber_subscribers_phone_n_369620_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Номер'),
        ),
    ]
