# Generated by Django 5.1.7 on 2025-03-11 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_subscriber_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История импорта', 'verbose_name_plural': 'История импорта'},
        ),
        migrations.RemoveField(
            model_name='importhistory',
            name='records_updated',
        ),
        migrations.AddField(
            model_name='importhistory',
            name='archive_table_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя архивной таблицы'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='delimiter',
            field=models.CharField(default=',', max_length=3, verbose_name='Разделитель'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='encoding',
            field=models.CharField(default='utf-8', max_length=20, verbose_name='Кодировка'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='has_header',
            field=models.BooleanField(default=True, verbose_name='Есть заголовок'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='records_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего записей'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='records_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Создано записей'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='records_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибочных записей'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
