# Generated by Django 5.1.7 on 2025-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_alter_importhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
