# Generated by Django 5.1.7 on 2025-03-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0005_alter_subscriber_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='info_message',
            field=models.TextField(blank=True, null=True, verbose_name='Информационное сообщение'),
        ),
    ]
