# Generated by Django 5.1.7 on 2025-08-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_importhistory_pause_cancel_heartbeat_and_errors'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='importerror',
            new_name='subscribers_import__456ea3_idx',
            old_name='subscribers_import_history_row_idx',
        ),
        migrations.RenameIndex(
            model_name='importerror',
            new_name='subscribers_created_b4117f_idx',
            old_name='subscribers_importerror_created_idx',
        ),
        migrations.AddField(
            model_name='importerror',
            name='raw_data',
            field=models.TextField(blank=True, null=True, verbose_name='Исходные данные строки'),
        ),
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('paused', 'Пауза'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
