# Generated by Django 5.1.7 on 2025-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_rename_subscribers_import_history_row_idx_subscribers_import__456ea3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerror',
            name='import_session_id',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='ID сессии импорта'),
        ),
        migrations.AddField(
            model_name='importhistory',
            name='import_session_id',
            field=models.CharField(default='', max_length=50, verbose_name='Уникальный ID сессии импорта'),
        ),
        migrations.AddIndex(
            model_name='importerror',
            index=models.Index(fields=['import_session_id', 'row_index'], name='subscribers_import__320d4a_idx'),
        ),
    ]
