# Generated by Django 5.1.7 on 2025-08-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_importerror_import_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='import_session_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Уникальный ID сессии импорта'),
        ),
    ]
