# Generated by Django 5.1.7 on 2025-08-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_make_import_session_id_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='importhistory',
            name='temp_table_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя временной таблицы'),
        ),
    ]
