# Generated by Django 5.1.7 on 2025-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0013_add_temp_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('paused', 'Пауза'), ('temp_completed', 'Импорт во временную таблицу завершен'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
