# Generated by Django 5.1.7 on 2025-09-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0015_increase_status_phase_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='status',
            field=models.CharField(choices=[('uploading', 'Загрузка файла'), ('pending', 'В ожидании'), ('processing', 'В обработке'), ('paused', 'Пауза'), ('temp_completed', 'Импорт во временную таблицу завершен'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=30, verbose_name='Статус'),
        ),
    ]
